--PROMPT PL/SQL Developer Export Tables for user IGE@MTB_LITSUP
--PROMPT Created by slee5 on June 24, 2019
-- SET FEEDBACK off
-- SET DEFINE off

--PROMPT Truncating IGE_SOURCE_H...
truncate table IGE_SOURCE_H;
--PROMPT Loading IGE_SOURCE_H...
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (137, 179, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'em-15B Mulock Av', to_timestamp('09-01-2009', 'dd-mm-yyyy'), 'em-15B Mulock Av', to_timestamp('09-01-2009', 'dd-mm-yyyy'), null, null, null, null, 'TORONTO', '15 Mulock Av renumbered to 15B Mulock Av; confirmation of 40 Cawthra Av split;', 'APPROVED', 0, 200207, 200237, 33);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (139, 182, 'REPORT', 'INHOUSE MAINTENANCE', 'em-321 York Mills Rd', to_timestamp('15-01-2009', 'dd-mm-yyyy'), 'em-321 York Mills Rd', to_timestamp('15-01-2009', 'dd-mm-yyyy'), null, null, null, null, 'NORTH YORK', '321 York Mills Rd, edit park name, former York Mills Park , now Irving Paisley Park; Jan 15, 2009, entrance for 2539 Bayview Av;', 'APPROVED', 0, 200211, 200237, 34);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (119, 137, 'REPORT', 'MUNICIPAL NUMBERING LETTER', '21, 23 Willowlea Dr', to_timestamp('29-12-2008', 'dd-mm-yyyy'), null, null, null, '64R-16569', null, null, 'SCARBOROUGH', 'In connection with the division of 21 Willowlea Dr, add 23 Willowlea Dr to identify a separate parcel (in IGE)', 'APPROVED', 0, 200104, 200114, 433);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (117, 133, 'REPORT', 'MUNICIPAL NUMBERING LETTER', '2 North Woodrow Blvd', to_timestamp('07-01-2009', 'dd-mm-yyyy'), null, null, null, '1882', null, null, 'SCARBOROUGH', 'Add address to an existing parcel', 'APPROVED', 0, 200093, 200114, 434);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (554, 965, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'em-21ColumbusAv', to_timestamp('08-09-2009', 'dd-mm-yyyy'), 'em-21ColumbusAv', to_timestamp('10-09-2009', 'dd-mm-yyyy'), null, null, null, null, null, 'em-add 21 Columbus Av; entr for 23; Sept 8, 2009', 'APPROVED', 0, 204387, 204389, 4321);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1090, 2119, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'JF-1239-1247AvenueRd', to_timestamp('10-05-2010', 'dd-mm-yyyy'), '2008195598NNY16SA', null, null, null, null, null, null, 'JF-MM-Add 229 - 239 Lytton Blvd as per JF-Sever-1239-1247AvenueRd-LyttonBlvd-20100510.pdf', 'APPROVED', 0, 208721, 208727, 12001);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1077, 2090, 'REPORT', 'BYLAW', 'By-Law 418-2010', to_timestamp('13-05-2010', 'dd-mm-yyyy'), null, null, null, null, null, null, null, 'Removing northbound one-way street on George St between Adelaide Street East and Richmond Street East', 'APPROVED', 0, 208576, 209393, 13281);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1129, 2207, 'REPORT', 'BYLAW', 'By-Law 314-1998', to_timestamp('11-06-2010', 'dd-mm-yyyy'), null, null, null, null, null, null, null, 'Adding one-way on Colborne Lodge Drive South of West Road to the southern most limit of the traffic island in the turning circle delineated by heavy lines on Map 4 at the end of this by-law', 'APPROVED', 0, 209008, 209393, 13282);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1167, 2313, 'REPORT', 'BYLAW', 'BY-LAW 162-1996', to_timestamp('24-06-2010', 'dd-mm-yyyy'), null, null, null, null, null, null, null, 'Changing one-way on Euclid Avenue from a point 62 metres north of Bloor Street West and Follis Avenue', 'APPROVED', 0, 209272, 209393, 13283);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (999, 1930, 'REPORT', 'BYLAW', 'By-Law 1995-132', to_timestamp('21-04-2010', 'dd-mm-yyyy'), null, null, null, null, null, null, null, 'By-law designating Jamestown Cres from John Garland Blvd to John Garland Blvd to a westbound one-way street.', 'APPROVED', 0, 208098, 209393, 13284);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1126, 2202, 'REPORT', 'BYLAW', 'By-Law 575-2010', to_timestamp('11-06-2010', 'dd-mm-yyyy'), null, null, null, null, null, null, null, 'Adding westbound one-way street on Wilton Street between Market Street and Jarvis Street', 'APPROVED', 0, 209008, 209393, 13285);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (990, 1910, 'REPORT', 'BYLAW', 'By-Law 351-2010', to_timestamp('19-04-2010', 'dd-mm-yyyy'), null, null, null, null, null, null, null, 'By-Law 351-2010 removes one-way street designation for Renfrew Pl between John Street and St. Patricks Market.', 'APPROVED', 0, 208052, 209393, 13286);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1131, 2214, 'REPORT', 'BYLAW', 'One-way Corrections', to_timestamp('14-06-2010', 'dd-mm-yyyy'), null, null, null, null, null, null, null, 'Correcting one-way streets found in turn restriction audit.', 'APPROVED', 0, 209052, 209468, 13601);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1258, 2553, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'em-11-61DocksideDr', to_timestamp('16-07-2010', 'dd-mm-yyyy'), 'em-11-61DocksideDr', to_timestamp('22-07-2010', 'dd-mm-yyyy'), null, null, null, null, null, 'em-add 115 Queens Quay East (Water''''s Edge Promenade), 11 Dockside Dr (see letter Nov 10, 2009) Sugar Beach Park, 61 Dockside Dr (Sherbourne Common South Park, 5 Lower Sherbourne Street (Sherbourne Common North Park); July 16, 2010', 'APPROVED', 0, 209871, 209942, 14561);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1644, 3482, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'JF-77SixteenthSt', to_timestamp('26-01-2011', 'dd-mm-yyyy'), 'B61/10EYK', to_timestamp('22-10-2010', 'dd-mm-yyyy'), null, null, null, null, null, 'JF-MM-Add 75 and 77 Sixteenth St as per JF-CofA-Sever-77SixteenthSt-20110126.pdf', 'APPROVED', 0, 212985, 213166, 19681);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1647, 3488, 'REPORT', 'INHOUSE MAINTENANCE', 'Azalea Crt', to_timestamp('17-03-2011', 'dd-mm-yyyy'), 'Tampa Ter', to_timestamp('17-03-2011', 'dd-mm-yyyy'), null, null, null, null, null, 'mm-Azalea Crt, Tampa Ter fix addr loc, fix addr range/Cadastral', 'APPROVED', 0, 212992, 213166, 19682);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1664, 3522, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'em-25ReesSt', to_timestamp('09-03-2011', 'dd-mm-yyyy'), 'em-25ReesSt', to_timestamp('21-03-2011', 'dd-mm-yyyy'), null, null, null, null, null, 'em-assign 25 Rees St; March 9, 2011', 'APPROVED', 0, 213036, 213166, 19683);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1643, 3480, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'JF-73SixteenthSt', to_timestamp('11-02-2011', 'dd-mm-yyyy'), 'B59/10EYK', to_timestamp('17-12-2010', 'dd-mm-yyyy'), null, null, null, null, null, 'JF-MM-Add 73A and 73B Sixteenth St as per JF-CofA-Sever-73SixteenthSt-20110211.pdf', 'APPROVED', 0, 212979, 213166, 19684);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1655, 3502, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'em-127-133Manville', to_timestamp('14-03-2011', 'dd-mm-yyyy'), 'em-127-133Manville', to_timestamp('21-03-2011', 'dd-mm-yyyy'), null, null, null, null, null, 'em-127 Manville Rd-prime, 133-entr; to assmt; March 14, 2011', 'APPROVED', 0, 213036, 213166, 19685);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1665, 3526, 'REPORT', 'MUNICIPAL NUMBERING LETTER', '1-19 Archemedes Crt', to_timestamp('22-03-2011', 'dd-mm-yyyy'), '1-19 Archemedes Crt', to_timestamp('17-02-2009', 'dd-mm-yyyy'), null, null, null, null, null, 'dm - moving addrs on Zaph Ave, Pythagoras Dr,,Archemedes Crt -SC ltr Feb 17/09', 'APPROVED', 0, 213046, 213166, 19686);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1663, 3520, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'em-194BurnettAv', to_timestamp('10-03-2011', 'dd-mm-yyyy'), 'B0006/09NY', to_timestamp('21-05-2010', 'dd-mm-yyyy'), null, null, null, null, null, 'em-cofa/omb for 194 Burnett Av; add 196; March 10, 2011', 'APPROVED', 0, 213036, 213166, 19687);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1666, 3529, 'REPORT', 'INHOUSE MAINTENANCE', '285 Dufferin St', to_timestamp('22-03-2011', 'dd-mm-yyyy'), '1182 King St W', to_timestamp('22-03-2011', 'dd-mm-yyyy'), null, null, null, null, null, '49G- add 285 Dufferin St, ENTR to 1182 King St W-Inq fr Police/LIM/EM', 'APPROVED', 0, 213093, 213166, 19688);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1648, 3489, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'JF-31BissetAv', to_timestamp('21-01-2011', 'dd-mm-yyyy'), 'B62/10EYK', to_timestamp('26-11-2010', 'dd-mm-yyyy'), null, null, null, null, null, 'JF-MM-Add 31 and 33 Bisset Av as per JF-CofA-Sever-31BissetAv-20110121.pdf', 'APPROVED', 0, 213013, 213166, 19689);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1660, 3513, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'em-33GouldSt', to_timestamp('16-03-2011', 'dd-mm-yyyy'), 'em-33GouldSt', to_timestamp('21-03-2011', 'dd-mm-yyyy'), null, null, null, null, null, 'em-add 33 Gould St, entr for 122 Bond St; March 16, 2011', 'APPROVED', 0, 213036, 213166, 19690);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1653, 3498, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'em-84B-Rosemount', to_timestamp('14-03-2011', 'dd-mm-yyyy'), 'em-84B-Rosemount', to_timestamp('21-03-2011', 'dd-mm-yyyy'), null, null, null, null, null, 'em-add 84B Rosemount Av, entr for 84; March 14, 2011', 'APPROVED', 0, 213036, 213166, 19691);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1656, 3504, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'em-119-123Manville', to_timestamp('14-03-2011', 'dd-mm-yyyy'), 'em-119-123Manville', to_timestamp('21-03-2011', 'dd-mm-yyyy'), null, null, null, null, null, 'em-add 123 Manville Rd, entr for 119; to assmt; range; March 14, 2011', 'APPROVED', 0, 213036, 213166, 19692);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1654, 3500, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'em-80RosemountAv', to_timestamp('14-03-2011', 'dd-mm-yyyy'), 'em-80RosemountAv', to_timestamp('21-03-2011', 'dd-mm-yyyy'), null, null, null, null, null, 'em-add 80 Rosemount Av; entr for 83 Glenholme Av; March 14, 2011', 'APPROVED', 0, 213036, 213166, 19693);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1640, 3473, 'REPORT', 'INHOUSE MAINTENANCE', '3393-3395 Yonge St', to_timestamp('16-03-2011', 'dd-mm-yyyy'), null, null, null, null, null, null, null, 'ld/51M-Delete ranged addr 3393-3395 Yonge St-not in mpac/req by IT-meena', 'APPROVED', 0, 212962, 213166, 19694);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1652, 3496, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'em-470BloorStW', to_timestamp('14-03-2011', 'dd-mm-yyyy'), 'em-470BloorStW', to_timestamp('21-03-2011', 'dd-mm-yyyy'), null, null, null, null, null, 'em-add 470 Bloor St W, entr for 468; March 14, 2011', 'APPROVED', 0, 213036, 213166, 19695);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1637, 3467, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'JF-74ClissoldRd', to_timestamp('03-03-2011', 'dd-mm-yyyy'), 'B85/10EYK', to_timestamp('28-01-2011', 'dd-mm-yyyy'), null, null, null, null, null, 'JF-MM-Add 74A and 74B Clissold Rd as per JF-CofA-Sever-74ClissoldRd-20110303.pdf', 'APPROVED', 0, 212936, 213166, 19696);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1645, 3483, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'JF-23KingdomSt', to_timestamp('26-01-2011', 'dd-mm-yyyy'), 'PL100644', to_timestamp('17-11-2010', 'dd-mm-yyyy'), null, null, null, null, null, 'JF-MM-Add 23 and 25 Kingdom St as per JF-CofA-Sever-23KingdomSt-20110126.pdf', 'APPROVED', 0, 212985, 213166, 19697);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1673, 3541, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'em-101-107ErskineAv', to_timestamp('24-03-2011', 'dd-mm-yyyy'), 'em-101-107ErskineAv', to_timestamp('25-03-2011', 'dd-mm-yyyy'), null, null, null, null, null, 'em-add 101 Erskine Av -res bldg, 107 Erskine Av-commerc units, to 66 Broadway Av; March 24, 2011', 'APPROVED', 0, 213151, 213166, 19698);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1650, 3491, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'JF-2CroydonRd', to_timestamp('08-03-2011', 'dd-mm-yyyy'), 'B0097/10TEY', to_timestamp('15-02-2011', 'dd-mm-yyyy'), null, null, null, null, null, 'JF-MM-Add 2A and 2B Croydon Rd as per JF-CofA-Sever-2CroydonRd-20110308.pdf', 'APPROVED', 0, 213013, 213166, 19699);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1670, 3536, 'REPORT', 'MUNICIPAL NUMBERING LETTER', '8 to 58 Jeremiah Lan', to_timestamp('23-03-2011', 'dd-mm-yyyy'), '8 to 58 Jeremiah Lan', to_timestamp('23-03-2011', 'dd-mm-yyyy'), null, null, null, null, null, 'dm - moving addrs - Jeremiah Lane / Scarborough Golf Club Rd - SC ltr Nov 25/10', 'APPROVED', 0, 213125, 213166, 19700);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1661, 3515, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'em-31NorthernPl', to_timestamp('16-03-2011', 'dd-mm-yyyy'), 'B0049/10TEY', to_timestamp('01-12-2010', 'dd-mm-yyyy'), null, null, null, null, null, 'em-cofa for 31 Northern Pl; add 31 Northern Pl, 49A, 49B, 49C Shirley St; March 16, 2011', 'APPROVED', 0, 213036, 213166, 19701);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1671, 3537, 'REPORT', 'MUNICIPAL NUMBERING LETTER', '10 Harlandale Ave', to_timestamp('25-03-2011', 'dd-mm-yyyy'), '10 Harlandale Ave', to_timestamp('25-03-2011', 'dd-mm-yyyy'), null, null, null, null, null, 'mm-10 Harlandale Ave fix addr loc/NyLet-Mar01/1994', 'APPROVED', 0, 213149, 213166, 19702);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1642, 3477, 'REPORT', 'INHOUSE MAINTENANCE', 'Toronto Islands Fcod', to_timestamp('16-03-2011', 'dd-mm-yyyy'), 'Shoreline-Trial', to_timestamp('16-03-2011', 'dd-mm-yyyy'), null, null, null, null, null, '50F-to modify feature code fr Shoreline to Trail-IT-Sepideh', 'APPROVED', 0, 212964, 213166, 19703);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (554, 967, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'em-23ColumbusAv', to_timestamp('08-09-2009', 'dd-mm-yyyy'), 'em-23ColumbusAv', to_timestamp('10-09-2009', 'dd-mm-yyyy'), null, null, null, null, null, 'em-add 23 Columbus Av; entr for 21; Sept 8, 2009', 'APPROVED', 0, 204389, 204390, 4322);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (847, 1609, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'JF-3105SheppardAvE', to_timestamp('12-02-2010', 'dd-mm-yyyy'), 'JF-3105SheppardAvE', null, null, null, null, null, null, 'JF-MM Add or move Nos. 3105-3133 Sheppard Avenue East as per JF-Range-Entrance-3105-3133SheppardAvE-20100212.pdf', 'APPROVED', 0, 206981, 206982, 8481);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (847, 1617, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'JF-3105SheppardAvE', to_timestamp('12-02-2010', 'dd-mm-yyyy'), 'JF-3105SheppardAvE', null, null, null, null, null, null, 'JF-DM Add or move Nos. 3105-3133 Sheppard Avenue East as per JF-Range-Entrance-3105-3133SheppardAvE-20100212.pdf', 'APPROVED', 0, 206982, 207194, 9121);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1032, 2004, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'JF-1152GlengroveAv', to_timestamp('29-04-2010', 'dd-mm-yyyy'), null, null, null, null, null, null, null, 'JF-MM Add 1150 Glengrove Av as per JF-Assign-1152GlenGroveAv-20100429.pdf', 'APPROVED', 0, 208269, 208273, 11681);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (595, 1062, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'JF-7 Richgrove Dr', to_timestamp('11-03-2009', 'dd-mm-yyyy'), 'JF-7 Richgrove Dr', null, null, null, null, null, null, 'JF-MM-Add 5, 25 and 35 Richgrove Dr as per JF-Condo-7-21RichgroveDr-20090311.pdf and JF-Assmt-Range-7-21RichgroveDr-20090311.pdf', 'APPROVED', 0, 204813, 208849, 12324);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1110, 2165, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'JF-Victoria-Leafield', to_timestamp('20-04-2010', 'dd-mm-yyyy'), '2007220578ESC40SB', to_timestamp('23-05-2007', 'dd-mm-yyyy'), null, null, null, null, null, 'JF-DM-Add 21-31B, 2-26 Leafield Dr as per JF-Subdivision-2787-2791VictoriaParkAv-LeafieldDr-20100420.pdf', 'APPROVED', 0, 208844, 209130, 12641);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1659, 3511, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'em-265-303Queen''s', to_timestamp('14-03-2011', 'dd-mm-yyyy'), 'B72/10EYK', to_timestamp('26-11-2010', 'dd-mm-yyyy'), null, null, null, null, null, 'em-sever/convey for 265 and 303 Queen''''s Dr; to 1779R Jane St; March 14, 2011', 'APPROVED', 0, 213036, 213166, 19704);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1651, 3495, 'REPORT', 'MUNICIPAL NUMBERING LETTER', '1-33  Hearth Pl', to_timestamp('21-03-2011', 'dd-mm-yyyy'), '1-33 Hearth Pl', to_timestamp('21-03-2011', 'dd-mm-yyyy'), null, null, null, null, null, 'dm - move 1 to 33 Hearth Pl to correct parcels', 'APPROVED', 0, 213030, 213166, 19705);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1649, 3490, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'JF-6490KingstonRd', to_timestamp('09-03-2011', 'dd-mm-yyyy'), 'B067/10SC', to_timestamp('20-01-2011', 'dd-mm-yyyy'), null, null, null, null, null, 'JF-DM-Add 6484-6490 Kingston Rd as per JF-CofA-Sever-6490KingstonRd-20110309.pdf', 'APPROVED', 0, 213013, 213166, 19706);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1638, 3468, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'JF-45VanscoRd', to_timestamp('11-03-2011', 'dd-mm-yyyy'), null, null, null, null, null, null, null, 'JF-MM-Add 35 North Queen St as per JF-Entrance-45VanscoRd-NorthQueenSt-20110311.pdf', 'APPROVED', 0, 212936, 213166, 19707);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1646, 3484, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'JF-4286LawrenceAvE', to_timestamp('28-01-2011', 'dd-mm-yyyy'), 'B033/09SC', to_timestamp('01-02-2011', 'dd-mm-yyyy'), null, null, null, null, null, 'JF-DM-Add 4286A, 4286B and 4288 Lawrence Av E as per JF-CofA-Sever-4286-4288LawrenceAvE-20110128.pdf', 'APPROVED', 0, 212985, 213166, 19708);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1669, 3534, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'JF-26AGreendaleAv', to_timestamp('21-03-2011', 'dd-mm-yyyy'), null, null, null, null, null, null, null, 'JF-DM-Change 28 to 26A Greendale Av as per JF-Assmt-Renumber-28GreendaleAv-20110321.pdf', 'APPROVED', 0, 213116, 213166, 19709);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1668, 3532, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'em-20-26ChurchillAv', to_timestamp('22-03-2011', 'dd-mm-yyyy'), '2010301409NNY23SA', to_timestamp('23-03-2011', 'dd-mm-yyyy'), null, null, null, null, null, 'em-admal 20, 22, 24, 26 Churchill Av, 31, 33, 37, 41, 45 Horsham Av; res condo 68 Canterbury Pl, and 20 towns: 76, 78 Canterbury Pl, 26 Churchill Av; 351-369 Beecroft Rd, 27-39 Horsham Av; March 22, 2011', 'APPROVED', 0, 213105, 213166, 19710);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1658, 3508, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'em-20JohnSt', to_timestamp('17-03-2011', 'dd-mm-yyyy'), '2010141300STE20CD', to_timestamp('21-03-2011', 'dd-mm-yyyy'), null, null, null, null, null, 'em-add 20 John St, second tower, one condo; 300 Front St W-prime; March 17, 2011', 'APPROVED', 0, 213036, 213166, 19711);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1674, 3543, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'Homestead Rd', to_timestamp('25-03-2011', 'dd-mm-yyyy'), 'Homestead Rd', to_timestamp('25-03-2011', 'dd-mm-yyyy'), null, null, null, null, null, 'dm - moving addrs to correct parcels - 145 to 155 Homestead Rd', 'APPROVED', 0, 213157, 213166, 19712);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1639, 3469, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'JF-99AHillCr', to_timestamp('15-03-2011', 'dd-mm-yyyy'), null, null, null, null, null, null, null, 'JF-DM-Delete 99A Hill Cr as per JF-Delete-99AHillCr-20110315.pdf', 'APPROVED', 0, 212936, 213166, 19713);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1657, 3506, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'em-29CivicRd', to_timestamp('14-03-2011', 'dd-mm-yyyy'), 'em-29CivicRd', to_timestamp('21-03-2011', 'dd-mm-yyyy'), null, null, null, null, null, 'em-add 29 Civic Rd; March 14, 2011', 'APPROVED', 0, 213036, 213166, 19714);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1672, 3538, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'em-1LeslieSt', to_timestamp('24-03-2011', 'dd-mm-yyyy'), 'em-1LeslieSt', to_timestamp('25-03-2011', 'dd-mm-yyyy'), null, null, null, null, null, 'em-add 1Leslie St, Tommy Thompson Park, March 24, 11', 'APPROVED', 0, 213151, 213166, 19715);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1662, 3518, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'em-2167LakeShore', to_timestamp('10-03-2011', 'dd-mm-yyyy'), 'em-2167LakeShore', to_timestamp('21-03-2011', 'dd-mm-yyyy'), null, null, null, null, null, 'em-add 2167 Lake Shore Blvd West, entr for 2165; sales office; March 10, 2011', 'APPROVED', 0, 213036, 213166, 19716);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1667, 3531, 'REPORT', 'MUNICIPAL NUMBERING LETTER', '3 to 50 Curran Hall', to_timestamp('23-01-2008', 'dd-mm-yyyy'), '3 to 50 Curran Hall', to_timestamp('23-03-2011', 'dd-mm-yyyy'), null, null, null, null, null, 'dm - move addrs - 3 to 50 Curran Hall Cres - SC ltr Jan 14/08', 'APPROVED', 0, 213103, 213166, 19717);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (135, 174, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'em-120 Grangeway Av', to_timestamp('14-01-2009', 'dd-mm-yyyy'), 'em-120 Grangeway Av', to_timestamp('14-01-2009', 'dd-mm-yyyy'), null, null, null, null, 'SCARBOROUGH', 'city-owned land; 120 Grangeway Av assigned by mun numbering letter Jan 14, 2009;', 'APPROVED', 0, 200196, 200244, 17);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (223, 317, 'REPORT', 'INHOUSE MAINTENANCE', 'Over/underpass', to_timestamp('02-03-2009', 'dd-mm-yyyy'), 'Over/underpass', null, null, null, null, null, null, 'Overpass underpass maintenance', 'APPROVED', 0, 200774, 200775, 97);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (275, 407, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'JF -74A, 74B Yore Rd', to_timestamp('19-03-2009', 'dd-mm-yyyy'), 'JF -74A, 74B Yore Rd', null, null, null, null, null, null, null, 'APPROVED', 0, 201554, 201555, 418);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (342, 533, 'REPORT', 'BYLAW', 'BY-LAW 325-2009', to_timestamp('22-04-2009', 'dd-mm-yyyy'), null, null, null, null, null, null, null, 'Adding One-way on Concord Avenue from Hepbourne Street and Bloor Street West.', 'APPROVED', 0, 202412, 202417, 785);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (149, 207, 'REPORT', 'MUNICIPAL NAMING LETTER', 'MM 338  Falstaff Ave', to_timestamp('06-01-2009', 'dd-mm-yyyy'), 'MM 340 Falstaff Ave', to_timestamp('22-01-2009', 'dd-mm-yyyy'), null, null, null, null, 'NORTH YORK', 'MM 47M-Modify 338,340 Falstaff Ave(loc and f.code)/Let-6Jan2009/PhotoImagery2005', 'APPROVED', 0, 200280, 206362, 7217);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1229, 2475, 'REPORT', 'MUNICIPAL NUMBERING LETTER', '11-23 NancyPocockPl', to_timestamp('09-07-2010', 'dd-mm-yyyy'), '11-23 NancyPocockPl', to_timestamp('27-01-2001', 'dd-mm-yyyy'), null, null, null, null, null, '49H23-To move 11 to 23 Nancy Pocock Pl into the correct parcels-Torlet 27Jan2001/cadastral', 'APPROVED', 0, 209576, 210577, 16161);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1527, 3187, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'JF-1730NeilsonRd', to_timestamp('09-07-2010', 'dd-mm-yyyy'), 'B021/09SC', to_timestamp('09-11-2009', 'dd-mm-yyyy'), null, null, null, null, null, 'JF-DM-Add 1730 Neilson Rd and 2710, 2750 Morningside Av as per JF-CofA-Sever-MorningsideAv-NeilsonRd-20100709.pdf', 'APPROVED', 0, 211892, 211962, 17442);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1579, 3319, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'JF-31-53SaulterSt', to_timestamp('11-02-2011', 'dd-mm-yyyy'), null, null, null, null, null, null, null, 'JF-LD-Add 31,33,53-67 Saulter St as per JF-Assmt-SaulterSt-StrangeSt-20110211.pdf and JF-Assign-SaulterSt-20101130.pdf', 'APPROVED', 0, 212402, 212501, 18721);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (135, 197, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'em-120 Grangeway Av', to_timestamp('14-01-2009', 'dd-mm-yyyy'), 'em-120 Grangeway Av', to_timestamp('14-01-2009', 'dd-mm-yyyy'), null, null, null, null, 'SCARBOROUGH', 'city-owned land; 120 Grangeway Av assigned by mun numbering letter Jan 14, 2009;', 'APPROVED', 0, 200244, 200252, 18);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (606, 1090, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'ld/133 The Kingsway', to_timestamp('06-10-2009', 'dd-mm-yyyy'), 'edit133XTheKingsway', to_timestamp('06-10-2009', 'dd-mm-yyyy'), null, null, null, null, null, 'Ld/46J21-Edit 133X to 133 The Kingsway-Torlet 6Oct2009', 'APPROVED', 0, 204950, 204962, 5281);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1001, 1947, 'REPORT', 'MUNICIPAL NAMING LETTER', 'JF-150RimrockRd', to_timestamp('24-12-2009', 'dd-mm-yyyy'), '09 113777 NNY 08 SA', to_timestamp('13-01-2010', 'dd-mm-yyyy'), null, null, null, null, null, 'JF-MM-Add 1119 and 1123 Lodestar Rd as per JF-Amalg-Entrance-150RimrockRd-1115LodestarRd-20091224.pdf', 'APPROVED', 0, 208123, 208125, 11045);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1001, 1949, 'REPORT', 'MUNICIPAL NAMING LETTER', 'JF-150RimrockRd', to_timestamp('24-12-2009', 'dd-mm-yyyy'), '2009113777NNY08SA', to_timestamp('13-01-2010', 'dd-mm-yyyy'), null, null, null, null, null, 'JF-MM-Add 1119 and 1123 Lodestar Rd as per JF-Amalg-Entrance-150RimrockRd-1115LodestarRd-20091224.pdf', 'APPROVED', 0, 208125, 208126, 11046);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1001, 1951, 'REPORT', 'MUNICIPAL NAMING LETTER', 'JF-150RimrockRd', to_timestamp('24-12-2009', 'dd-mm-yyyy'), '2009113777NNY08SA', null, null, null, null, null, null, 'JF-MM-Add 1119 and 1123 Lodestar Rd as per JF-Amalg-Entrance-150RimrockRd-1115LodestarRd-20091224.pdf', 'APPROVED', 0, 208126, 208127, 11047);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1102, 2142, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'em-742TheQueensway', to_timestamp('20-05-2010', 'dd-mm-yyyy'), 'em-742TheQueensway', to_timestamp('27-05-2010', 'dd-mm-yyyy'), null, null, null, null, null, 'em-new boundaries, new roll for 742 TQ; May 20, 2010', 'APPROVED', 0, 208769, 208783, 12321);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1098, 2134, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'em-724TheQueensway', to_timestamp('20-05-2010', 'dd-mm-yyyy'), 'em-724TheQueensway', to_timestamp('27-05-2010', 'dd-mm-yyyy'), null, null, null, null, null, 'em-add 724 The Queensway, prime, add 726 TQ-entr ; May 20, 2010', 'APPROVED', 0, 208769, 208783, 12322);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (142, 189, 'REPORT', 'MUNICIPAL NUMBERING LETTER', '13 Jillson Av', to_timestamp('26-11-2008', 'dd-mm-yyyy'), null, null, null, null, null, null, 'YORK', 'JF/MM - Delete 13 Jillson Av as per JF-Assmt-13JillsonAv-20081126.doc', 'APPROVED', 0, 200234, 200238, 66);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (356, 561, 'REPORT', 'INHOUSE MAINTENANCE', 'JEANETTE ST', to_timestamp('24-04-2009', 'dd-mm-yyyy'), null, null, null, null, null, null, null, 'Removing one-way coding from segments on Jeanette st that were accidentally coded as one-way.', 'APPROVED', 0, 202500, 202504, 1121);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (480, 838, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'JF-21-23 Roycrest Av', to_timestamp('24-04-2009', 'dd-mm-yyyy'), 'JF-21-23 Roycrest Av', to_timestamp('07-03-2008', 'dd-mm-yyyy'), null, null, null, null, null, 'JF-MM-Add 25 Roycrest Av and 370 Sheppard Av W as per JF-CofA-Sever-Renumber-21-23RoycrestAv-20090423.pdf', 'APPROVED', 0, 203918, 203927, 3041);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (526, 926, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'JF-2787 VictoriaPark', to_timestamp('04-09-2009', 'dd-mm-yyyy'), 'JF-2787 VictoriaPark', to_timestamp('10-09-2008', 'dd-mm-yyyy'), null, null, null, null, null, 'JF-DM-Add 2787A and B Victoria Park Av as per JF-CofA-Sever-2787VictoriaParkAv-20090904.pdf', 'APPROVED', 0, 204326, 204332, 4001);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (872, 1657, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'JF-333BloorStE', to_timestamp('02-12-2009', 'dd-mm-yyyy'), 'JF-333BloorStE', null, null, null, null, null, null, 'JF-LD-Add 1 Ted Rogers Way as per JF-Renumber-Rename-777JarvisSt-333BloorStE-TedRogersWay-20091202.pdf', 'APPROVED', 0, 207160, 207262, 9441);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1002, 1938, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'JF-74-76PortageAv', to_timestamp('26-10-2009', 'dd-mm-yyyy'), 'PL081318', to_timestamp('24-02-2009', 'dd-mm-yyyy'), null, null, null, null, null, 'JF-MM-Add 76 Portage Av as per JF-CofA-Sever-74-76PortageAv-20091026.pdf', 'APPROVED', 0, 208112, 208115, 11041);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1001, 1937, 'REPORT', 'MUNICIPAL NAMING LETTER', 'JF-150RimrockRd', to_timestamp('24-12-2009', 'dd-mm-yyyy'), null, null, null, null, null, null, null, 'JF-MM-Add 1119 and 1123 Lodestar Rd as per JF-Amalg-Entrance-150RimrockRd-1115LodestarRd-20091224.pdf', 'APPROVED', 0, 208112, 208115, 11042);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1001, 1941, 'REPORT', 'MUNICIPAL NAMING LETTER', 'JF-150RimrockRd', to_timestamp('24-12-2009', 'dd-mm-yyyy'), '09 113777 NNY 08 SA', null, null, null, null, null, null, 'JF-MM-Add 1119 and 1123 Lodestar Rd as per JF-Amalg-Entrance-150RimrockRd-1115LodestarRd-20091224.pdf', 'APPROVED', 0, 208115, 208120, 11043);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1001, 1943, 'REPORT', 'MUNICIPAL NAMING LETTER', 'JF-150RimrockRd', to_timestamp('24-12-2009', 'dd-mm-yyyy'), '09 113777 NNY 08 SA', null, null, null, null, null, null, 'JF-MM-Add 1119 and 1123 Lodestar Rd as per JF-Amalg-Entrance-150RimrockRd-1115LodestarRd-20091224.pdf', 'APPROVED', 0, 208120, 208123, 11044);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (843, 1600, 'REPORT', 'MUNICIPAL NUMBERING LETTER', '2555 St Clair Ave W', to_timestamp('16-02-2010', 'dd-mm-yyyy'), '2561-2569StClairAveW', to_timestamp('21-05-2009', 'dd-mm-yyyy'), null, null, null, null, null, 'Ld/47J21-Add ENTR 2561, 2565, 2567, 2569 to 2555 St Clair Ave W-Torlet 21May2009 for JF', 'APPROVED', 0, 206942, 212345, 18081);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (354, 558, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'em-185 Oasis Blvd', to_timestamp('23-04-2009', 'dd-mm-yyyy'), 'em-185 Oasis Blvd', to_timestamp('23-04-2009', 'dd-mm-yyyy'), null, null, null, null, null, 'em-assign 185 Oasis Blvd; former 1841 Neilson Rd; April 23, 2009', 'APPROVED', 0, 202479, 212371, 18401);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (185, 267, 'REPORT', 'BYLAW', 'Ln W Browns N Burlin', to_timestamp('04-02-2009', 'dd-mm-yyyy'), 'Ln W Browns N Burlin', to_timestamp('04-02-2009', 'dd-mm-yyyy'), null, null, null, null, null, 'mm 42F Add Ln W Browns N Burlingame/EB-129443/APSET-42F210401', 'APPROVED', 0, 200451, 200455, 81);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (319, 494, 'REPORT', 'BYLAW', 'BY-LAW 303-2005', null, null, null, null, null, null, null, null, 'Change one-way segment to two-way segment on Dalhousie St at Dundas St E.', 'APPROVED', 0, 202126, 202128, 770);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (209, 300, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'em-18-20 Maxome Av', to_timestamp('18-02-2009', 'dd-mm-yyyy'), 'em-18-20 Maxome Av', to_timestamp('18-02-2009', 'dd-mm-yyyy'), null, null, null, null, null, 'em- 232 Pemberton Av, add 18, 20 Maxome Av, new houses; Feb 18, 2009;', 'APPROVED', 0, 200604, 202896, 1761);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (380, 609, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'em-431RimiltonAv', to_timestamp('12-05-2009', 'dd-mm-yyyy'), 'em-431RimiltonAv', to_timestamp('12-05-2009', 'dd-mm-yyyy'), null, null, null, null, null, 'em-cofa 431 Rimilton Av; (431A, 431B  Rimilton Av; May 12, 2009', 'APPROVED', 0, 202840, 202896, 1762);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (379, 607, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'em-92-96CameronAv', to_timestamp('11-05-2009', 'dd-mm-yyyy'), 'em-92-96CameronAv', to_timestamp('12-05-2009', 'dd-mm-yyyy'), null, null, null, null, null, 'em-add 92, 94, 96 Cameron Av; CofA May 11, 2009', 'APPROVED', 0, 202834, 202896, 1763);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (374, 602, 'REPORT', 'INHOUSE MAINTENANCE', 'em-140-150Murison', to_timestamp('08-05-2009', 'dd-mm-yyyy'), 'em-140-150Murison', to_timestamp('08-05-2009', 'dd-mm-yyyy'), null, null, null, null, null, 'em-add 140, 150 Murison Blvd, in Scarb Feb 1, 1982', 'APPROVED', 0, 202767, 202896, 1764);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (293, 443, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'em-92MasonRd', to_timestamp('24-03-2009', 'dd-mm-yyyy'), 'em-cofa-92MasonRd', to_timestamp('24-03-2009', 'dd-mm-yyyy'), null, null, null, null, null, 'em-cofa-92 Mason Rd, 175 Adanac Dr; letter March 24, 2009;', 'APPROVED', 0, 201762, 202896, 1765);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (294, 445, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'em-39 St. AndrewsBlv', to_timestamp('24-03-2009', 'dd-mm-yyyy'), 'em-39StAndrewsBlvd', to_timestamp('24-03-2009', 'dd-mm-yyyy'), null, null, null, null, null, 'em- CofA 39 St. Andrews Blvd;March 24, 2009; add 35, 37 St. Andrews Blvd', 'APPROVED', 0, 201773, 202896, 1766);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (252, 369, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'em-4 Astoria Av', to_timestamp('12-03-2009', 'dd-mm-yyyy'), 'em-4 Astoria Av', to_timestamp('12-03-2009', 'dd-mm-yyyy'), null, null, null, null, null, 'em - OMB - 4 Astoria Av; 1A, 1B, 1C, 1D Elhurst Court; March 12, 2009;', 'APPROVED', 0, 201184, 202896, 1767);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (131, 165, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'em-185 Yorkland Blvd', to_timestamp('15-12-2008', 'dd-mm-yyyy'), '195 Yorkland Blvd', to_timestamp('29-10-2008', 'dd-mm-yyyy'), null, '66R-24059', null, null, 'NORTH YORK', 'OMB dec - Oct 29, 2008, sever 185 Yorkland Blvd into 2; mun lett Dec 15, 2008', 'APPROVED', 0, 200149, 202896, 1768);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (181, 262, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'em-416 Kingston Rd', to_timestamp('03-02-2009', 'dd-mm-yyyy'), 'em-416 Kingston Rd', to_timestamp('07-01-2009', 'dd-mm-yyyy'), null, null, null, null, null, 'em-CofA B0059/08TEY, 416 Kingston Rd & 73A Corley Av, adjust parcels;letter Feb 3, 2009; 66R-24155', 'APPROVED', 0, 200437, 202896, 1769);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (155, 219, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'em-68BrendaCr', to_timestamp('20-01-2009', 'dd-mm-yyyy'), 'em-68BrendaCr', to_timestamp('02-04-2008', 'dd-mm-yyyy'), null, '66R-23996', null, null, 'SCARBOROUGH', 'em-68 Brenda Cr , sever CofA (B028/08SC)dated April 2, 2008, mun numbering letter Jan 20, 2009, 68A, 68B Brenda Cr added;', 'APPROVED', 0, 200307, 202896, 1770);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (313, 483, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'em-cofa-196clanton', to_timestamp('02-04-2009', 'dd-mm-yyyy'), 'em-cofa-196clanton', to_timestamp('02-04-2009', 'dd-mm-yyyy'), null, null, null, null, null, 'em-cofa-196, 198, 200 Clanton Park Rd; April 2, 2009', 'APPROVED', 0, 202041, 202896, 1771);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (205, 290, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'em-2996-3004Bayview', to_timestamp('12-02-2009', 'dd-mm-yyyy'), 'em-2996-3004Bayview', to_timestamp('12-02-2009', 'dd-mm-yyyy'), null, null, null, null, null, 'em-2996-3004 Bayview Av, 14 townhhouses, 2 detached (incl Kingsdale Av, Emress Av); letter Feb 12, 2009;', 'APPROVED', 0, 200568, 202896, 1772);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (386, 621, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'em-34SherbourneStN', to_timestamp('13-05-2009', 'dd-mm-yyyy'), 'em-34SherbourneStN', to_timestamp('13-05-2009', 'dd-mm-yyyy'), null, null, null, null, null, 'em-cofa 32, 34 Sherbourne St North; May 13, 2009', 'APPROVED', 0, 202882, 202896, 1773);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (263, 385, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'em-100Queen''''sPark', to_timestamp('18-03-2009', 'dd-mm-yyyy'), 'em-100Queen''''sPark', to_timestamp('18-03-2009', 'dd-mm-yyyy'), null, null, null, null, null, 'em-cofa-90, 100 Queen''''s Park; March 18, 2009', 'APPROVED', 0, 201368, 202896, 1774);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (412, 695, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'JF-276-280Searle Av', to_timestamp('20-04-2009', 'dd-mm-yyyy'), 'JF-276-280Searle Av', to_timestamp('23-04-2008', 'dd-mm-yyyy'), null, null, null, null, null, 'Add 276A, 276B, 278 Searle Avenue and 319 Brighton Avenue as per JF-CofA-Sever-276-280SearleAv-20090420.pdf and (sketch) 276-280SearleAv-BrightonAv.pdf', 'APPROVED', 0, 203120, 203145, 2721);
--commit;
--PROMPT 100 records committed...
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (480, 842, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'JF-21-23 Roycrest Av', to_timestamp('24-04-2009', 'dd-mm-yyyy'), 'JF-21-23 Roycrest Av', to_timestamp('07-03-2008', 'dd-mm-yyyy'), null, null, null, null, null, 'JF-MM-Add 25 Roycrest Av and 370 Sheppard Av W as per JF-CofA-Sever-Renumber-21-23RoycrestAv-20090423.pdf NOTE: 23 Roycrest included in site area because it must be renumbered to faciliate new numbering for 21 Roycrest', 'APPROVED', 0, 203927, 203956, 3361);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (584, 1041, 'REPORT', 'INHOUSE MAINTENANCE', 'Ld/Add 44 Aileen Ave', to_timestamp('24-09-2009', 'dd-mm-yyyy'), null, null, null, null, null, null, null, 'Ld/48K-Add 44 Aileen Ave-Solid Waste-Bins/FC 18Sept2009/jf-ML will follow', 'APPROVED', 0, 204709, 204788, 4961);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (630, 1137, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'em-3710BloorStW', to_timestamp('20-10-2009', 'dd-mm-yyyy'), 'e,-3710BloorStW', to_timestamp('20-10-2009', 'dd-mm-yyyy'), null, null, null, null, null, 'em-add 3710 Bloor St West, struct for 3 Summerland Ter, block of towns; letter Nov 27, 2008', 'APPROVED', 0, 205140, 205142, 5601);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (223, 318, 'REPORT', 'INHOUSE MAINTENANCE', 'Over/underpass', to_timestamp('02-03-2009', 'dd-mm-yyyy'), 'Over/underpass', null, null, null, null, null, null, 'Overpass underpass maintenance', 'APPROVED', 0, 200775, 205919, 6561);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (710, 1293, 'REPORT', 'INHOUSE MAINTENANCE', 'BettySutherland', to_timestamp('24-11-2009', 'dd-mm-yyyy'), 'BettySutherland', to_timestamp('24-11-2009', 'dd-mm-yyyy'), null, null, null, null, null, 'Renaming of a portion East Don River Trail to Betty Sutherland Trail', 'APPROVED', 0, 205732, 205919, 6562);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (215, 307, 'REPORT', 'INHOUSE MAINTENANCE', 'Cycle Paths', to_timestamp('25-02-2009', 'dd-mm-yyyy'), 'Cycle Paths - 2009', to_timestamp('25-02-2009', 'dd-mm-yyyy'), null, null, null, null, null, 'TRANSPORTATION SERVICES - INFRASTRUCTURE - PEDESTRIAN & CYCLING  INFRATRUCTURE', 'APPROVED', 0, 200639, 205919, 6563);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (804, 1510, 'REPORT', 'INHOUSE MAINTENANCE', 'Move 366 Main St', to_timestamp('01-02-2010', 'dd-mm-yyyy'), '366 Main St into TO', to_timestamp('01-02-2010', 'dd-mm-yyyy'), null, null, null, null, null, 'Ld/54J-Move into Toronto parcel (dual mun.)366 Maint St-Cadstral/Mpac/assmt/IT Meena', 'APPROVED', 0, 206565, 206569, 7521);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (899, 1712, 'REPORT', 'INHOUSE MAINTENANCE', 'del 15-25 Grange Rd', to_timestamp('09-03-2010', 'dd-mm-yyyy'), 'Range 1-25 GrangeAve', to_timestamp('09-03-2010', 'dd-mm-yyyy'), null, null, null, null, null, 'ld/50H-expire range addr 15-25 Grange Ave-FC & not found- 2Mar2010. Mapc has #25 as PRM.', 'APPROVED', 0, 207396, 207399, 9761);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1246, 2525, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'JF-Hillary-Keele', to_timestamp('01-06-2010', 'dd-mm-yyyy'), 'B64/09EYK', to_timestamp('01-04-2010', 'dd-mm-yyyy'), null, null, null, null, null, 'JF-DM-Add 58-62 Hillary Av as per JF-IGE-Temporary-1533-1535KeeleSt-HillaryAv-20100601.pdf and JF-CofA-Sever-KeeleSt-HillaryAv-20100601.pdf', 'APPROVED', 0, 209721, 209729, 14241);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (599, 1073, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'em-115BlackCreekDr', to_timestamp('30-09-2009', 'dd-mm-yyyy'), 'em-115BlackCreekDr', to_timestamp('01-10-2009', 'dd-mm-yyyy'), null, null, null, null, null, 'em-add 115 Black Creek Dr; city-owned; Sept 30, 09', 'APPROVED', 0, 204818, 211614, 17121);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1529, 3193, 'REPORT', 'INHOUSE MAINTENANCE', 'LEASIDE RAILPATH TRL', to_timestamp('17-01-2011', 'dd-mm-yyyy'), null, null, null, null, null, null, null, null, 'APPROVED', 0, 211920, 211924, 17441);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1590, 3349, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'JF-333KingStE', to_timestamp('15-02-2011', 'dd-mm-yyyy'), null, null, null, null, null, null, null, 'JF-LD-Add 200, 222, 226, 230 Front St E as per JF-Entrance-333KingStE-FrontStE-20110215.pdf', 'APPROVED', 0, 212502, 212538, 19041);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (347, 545, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'JF-18 Dacre Cr', to_timestamp('25-02-2009', 'dd-mm-yyyy'), 'JF-18 Dacre Cr', null, null, null, null, null, null, null, 'APPROVED', 0, 202474, 202546, 801);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (372, 594, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'JF-5290 Yonge St', to_timestamp('11-02-2009', 'dd-mm-yyyy'), 'JF-5290 Yonge St', to_timestamp('19-11-2008', 'dd-mm-yyyy'), null, null, null, null, null, 'JF-MM-Add 1 Canterbury Place as per JF-CofA-Sever-5270-5290YongeSt-CanterburyPl-20090211.pdf', 'APPROVED', 0, 202720, 202723, 1441);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (775, 1448, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'JF-32A PreaknessDr', to_timestamp('22-09-2009', 'dd-mm-yyyy'), 'JF-32A PreaknessDr', null, null, null, null, null, null, 'JF-MM-Add 34 Preakness Drive as per JF-Renumber-32APreaknessDr-20091110.pdf', 'APPROVED', 0, 206204, 206211, 6881);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (829, 1563, 'REPORT', 'MUNICIPAL NUMBERING LETTER', '5 LowerSherbourneSt', to_timestamp('11-02-2010', 'dd-mm-yyyy'), '5 LowerSherbourneSt', to_timestamp('06-04-2009', 'dd-mm-yyyy'), null, null, null, null, null, 'ld/51G12-Amalgamate 5 Lower Sherbourne St, 190 Queens Quay East & 12 Bonnycastle St to 5 Lower Sherbourne St(park); & 12 Bonnycastle St (mixed-use devlt)-CoA B0110-0111/08TEY / Torlet 6April2009 for JF', 'APPROVED', 0, 206828, 206846, 8167);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (901, 1717, 'REPORT', 'MUNICIPAL NUMBERING LETTER', '115 Richview Ave', to_timestamp('10-03-2010', 'dd-mm-yyyy'), 'OMB PL081582 6May09', to_timestamp('25-03-2010', 'dd-mm-yyyy'), null, null, null, null, null, 'ld/50K21- sever 115 Richview Ave to 109, 111, 115- Torlet 25May2009 for JF', 'APPROVED', 0, 207417, 207423, 10081);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (639, 1161, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'Ld/36 Altamont Rd', to_timestamp('22-10-2009', 'dd-mm-yyyy'), 'Add 36 Altamont Rd', to_timestamp('22-10-2009', 'dd-mm-yyyy'), null, null, null, null, null, 'Ld/50Q-Add 36 Altamont Rd aroll 1908073190024700000-Bin/Mpac/ cadastral/ ML will be added byJF', 'APPROVED', 0, 205212, 207454, 10721);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1047, 2032, 'REPORT', 'INHOUSE MAINTENANCE', '885-887 O''Connor Dr', to_timestamp('05-05-2010', 'dd-mm-yyyy'), '885-887 O''Connor Dr', to_timestamp('04-05-2010', 'dd-mm-yyyy'), null, null, null, null, null, 'ld/54K- add 885 885A 887 O''''connor Dr-FC 4May2010/Mpac/EYrefmap #5/311', 'APPROVED', 0, 208387, 208807, 12323);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (694, 1260, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'em-742ScarlettRd', to_timestamp('10-11-2009', 'dd-mm-yyyy'), 'em-742ScarlettRd', to_timestamp('10-11-2009', 'dd-mm-yyyy'), null, null, null, null, null, 'em-add 2 Yorkleilgh Av, renumb from 742 Scarlett Rd; Nov 10, 09', 'APPROVED', 0, 205504, 210435, 15521);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1606, 3395, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'em-39-41BeathSt', to_timestamp('18-02-2011', 'dd-mm-yyyy'), 'em-39-41BeathSt', to_timestamp('24-02-2011', 'dd-mm-yyyy'), null, null, null, null, null, 'em-cofa for 39 Beath St, add 41; Feb 18, 2011', 'APPROVED', 0, 212613, 212625, 19361);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (359, 565, 'REPORT', 'MUNICIPAL NUMBERING LETTER', '5404 Lawrence Ave E', to_timestamp('28-04-2009', 'dd-mm-yyyy'), '5404 Lawrence Ave E', to_timestamp('28-04-2009', 'dd-mm-yyyy'), null, null, null, null, null, 'dm - adding ENTR -5504 Lawrence Ave E -MPAC', 'APPROVED', 0, 202517, 202578, 802);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (494, 862, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'JF-736-738 Kingston', to_timestamp('05-05-2009', 'dd-mm-yyyy'), 'JF-736-738 Kingston', null, null, null, null, null, null, 'JF-DM-Amalgamate 736-738 Kingston Rd as per JF-Amalg-Condo-736-738KingstonRd-20090505.pdf', 'APPROVED', 0, 204066, 204070, 3681);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (815, 1534, 'REPORT', 'MUNICIPAL NUMBERING LETTER', '2065 Kennedy Rd', to_timestamp('26-02-2009', 'dd-mm-yyyy'), '26,50 Village Green', to_timestamp('08-02-2010', 'dd-mm-yyyy'), null, null, null, null, null, 'dm - adding 26,50 Village Green Sq - deleting 2065 Kennedy Rd - Torlet Feb 26/09 / Map 56N-22', 'APPROVED', 0, 206729, 212317, 17761);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1007, 1958, 'REPORT', 'MUNICIPAL NUMBERING LETTER', '51 Montressor Dr', to_timestamp('23-04-2010', 'dd-mm-yyyy'), '6 Toba Dr', to_timestamp('12-06-2009', 'dd-mm-yyyy'), null, null, null, null, null, 'ld/51N23-sever 51 Montressor Dr to 51 & 6 Toba Dr-NYlet 12June2009 for JF', 'APPROVED', 0, 208142, 208150, 11361);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1152, 2273, 'REPORT', 'BYLAW', 'BY-LAW 162-1996', null, null, null, null, null, null, null, null, 'Changing one-way on Clinton Street from a point 61 metres north of Bloor Street West and Barton Avenue; Changing one-way on Clinton Street from a point 107 metres north of College Street and Bloor Street West', 'APPROVED', 0, 209203, 209210, 12961);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1350, 2772, 'REPORT', 'INHOUSE MAINTENANCE', '(proposed)Roper Rd', to_timestamp('10-09-2010', 'dd-mm-yyyy'), 'at Warden St', to_timestamp('10-09-2010', 'dd-mm-yyyy'), null, null, null, null, null, '55K13-Connect the proposed rd-Roper Rd (66M-2443 25/09/2007) to Mendelssohn St as requested by EMS/JC emailed 10sep2010, discussed w/ BrianH & HishamM.', 'APPROVED', 0, 210543, 210550, 15841);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (296, 448, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'em-5MerrillAv', to_timestamp('24-03-2009', 'dd-mm-yyyy'), 'em-5MerrillAv', to_timestamp('24-03-2009', 'dd-mm-yyyy'), null, null, null, null, null, 'em-5 Merrill Av, Merrill Park, lett March 24, 2009', 'APPROVED', 0, 201818, 201822, 449);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (585, 1043, 'REPORT', 'INHOUSE MAINTENANCE', 'em-1513-1537Davenp', to_timestamp('24-09-2009', 'dd-mm-yyyy'), 'em-1513-1537Davenp', to_timestamp('24-09-2009', 'dd-mm-yyyy'), null, null, null, null, null, 'em-add 1513-1537 Davenport  Rd, entr for 1541 ; in LIM, prop data map; Sept 24, 09', 'APPROVED', 0, 204711, 204715, 4641);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (416, 703, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'em-620DundasStE', to_timestamp('03-06-2009', 'dd-mm-yyyy'), 'em-39OakSt-42ColeSt', to_timestamp('04-06-2009', 'dd-mm-yyyy'), null, null, null, null, null, 'em-pt of 620 Dundas St E; block 12 ; add 39 Oak St and 42 Cole St (primes) and 41-65 Oak St, 44-68 Cole St, 101-107 Regent St; June 3, 2009;', 'APPROVED', 0, 203124, 205748, 6241);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1321, 2698, 'REPORT', 'MUNICIPAL NUMBERING LETTER', '502SammonAv', to_timestamp('25-08-2010', 'dd-mm-yyyy'), '502SammonAv', to_timestamp('26-08-2010', 'dd-mm-yyyy'), null, null, null, null, null, 'em-assign 502 Sammon Av; Aug 25, 2010', 'APPROVED', 0, 210345, 210383, 15201);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (167, 238, 'REPORT', 'MUNICIPAL NUMBERING LETTER', '50 Glen Cedar Road', to_timestamp('19-12-2008', 'dd-mm-yyyy'), null, null, null, null, null, null, 'YORK', 'JF/MM  Add 50 Glen Cedar Road as LE to identify existing parcel of land as per JF-Assmt-Parks-GlenCedarRd-WinonaDr-20081220.pdf', 'APPROVED', 0, 200354, 200370, 65);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (270, 394, 'REPORT', 'MUNICIPAL NUMBERING LETTER', '8 The Esplande', to_timestamp('08-01-2009', 'dd-mm-yyyy'), '8 The Esplande', null, null, null, null, null, null, 'JF add 8 The Esplanade as a proposed L, S, SE for 1 Front St East as per JF-Reserve-Condo-1FrontStE-TheEsplanade-20090108.pdf', 'APPROVED', 0, 201471, 201549, 417);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (404, 673, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'JF-8 Duncan St', to_timestamp('09-04-2009', 'dd-mm-yyyy'), 'JF-8 Duncan St', null, null, null, null, null, null, 'JF-LD-Delete 8 Duncan St as per JF-ListA-Entrance-Delete-276KingStW-DuncanSt-20090409.doc', 'APPROVED', 0, 203037, 203042, 2081);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (634, 1150, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'JF-59-61GiltspurDr', to_timestamp('20-10-2009', 'dd-mm-yyyy'), 'JF-59-61GiltspurDr', null, null, null, null, null, null, 'JF-MM-Add 59,61 Giltspur Dr as per JF-Assign-GiltspurDr-20091020.pdf', 'APPROVED', 0, 205174, 205244, 5921);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (803, 1506, 'REPORT', 'MUNICIPAL NAMING LETTER', 'Lot Street Lane', to_timestamp('01-02-2010', 'dd-mm-yyyy'), 'Lot Street Lane', to_timestamp('28-01-2010', 'dd-mm-yyyy'), null, null, null, null, null, 'ld/50G22-Rename Ln S Queen E Spadina to ''''Lot Street Lane''''.- Apset50G220101/BHall emailed 28Jan2010', 'APPROVED', 0, 206554, 206693, 7843);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1264, 2574, 'REPORT', 'MUNICIPAL NUMBERING LETTER', '13B Rivitt Pl', to_timestamp('22-07-2010', 'dd-mm-yyyy'), '13B Rivitt Pl', to_timestamp('27-07-2010', 'dd-mm-yyyy'), null, null, null, null, null, 'dm - modify 13 Rivitt Pl to 13B - SC ltr Jul 22/10', 'APPROVED', 0, 209930, 210064, 14881);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1679, 3626, 'REPORT', 'INHOUSE MAINTENANCE', 'Sep-12Apr2011-VK', to_timestamp('12-04-2011', 'dd-mm-yyyy'), null, null, null, null, null, null, null, 'Test address re-link', 'PREAPPROVAL', 0, 213185, 213217, 20001);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (318, 492, 'REPORT', 'BYLAW', 'BY-LAW 799-2005', to_timestamp('08-04-2009', 'dd-mm-yyyy'), null, null, null, null, null, null, null, 'Change one-way street to two-way street on Lauder Ave at St. Clair Ave W.', 'APPROVED', 0, 202117, 202126, 769);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (632, 1147, 'REPORT', 'BYLAW', 'BY-LAW 926-2009', to_timestamp('20-10-2009', 'dd-mm-yyyy'), 'BY-LAW 926-2009', to_timestamp('20-10-2009', 'dd-mm-yyyy'), null, null, null, null, null, 'Removing one-way segment from Maitland Pl.', 'APPROVED', 0, 205164, 207144, 8801);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (631, 1141, 'REPORT', 'BYLAW', 'BY-LAW 850-2009', to_timestamp('20-10-2009', 'dd-mm-yyyy'), 'BY-LAW 850-2009', to_timestamp('20-10-2009', 'dd-mm-yyyy'), null, null, null, null, null, 'Removing one-way street segment on Remembrance Dr at Ontario Drive in order to allow for left turn restriction to be rescinded. the intersection has been reconfigured.', 'APPROVED', 0, 205154, 207144, 8802);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (480, 846, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'JF-21-Roycrest Av', to_timestamp('24-04-2009', 'dd-mm-yyyy'), 'JF-21-Roycrest Av', to_timestamp('07-03-2008', 'dd-mm-yyyy'), null, null, null, null, null, 'JF-MM- Reallocate 21 and 23 Roycrest Avenue and add and 370 Sheppard Av W as per JF-CofA-Sever-Renumber-21-23RoycrestAv-20090423.pdf', 'APPROVED', 0, 203956, 210691, 16481);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (484, 847, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'JF-23 Roycrest Av', to_timestamp('24-04-2009', 'dd-mm-yyyy'), 'JF-23 Roycrest Av', null, null, null, null, null, null, 'JF-MM- Add 25 Roycrest Avenue as per JF-CofA-Sever-Renumber-21-23RoycrestAv-20090423.pdf', 'APPROVED', 0, 203959, 210691, 16482);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (105, 108, 'REPORT', 'INHOUSE MAINTENANCE', '1087 Davenport Rd', to_timestamp('23-12-2008', 'dd-mm-yyyy'), 'solid waste', to_timestamp('18-12-2008', 'dd-mm-yyyy'), null, null, null, null, 'TORONTO', 'add entrance addresses: 1087C, D, E, F, G, H, J Davenport Rd, field check done Dec 18, 2008; municipal addressing letter will follow;', 'APPROVED', 0, 200024, 200028, 1);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (104, 107, 'REPORT', 'INHOUSE MAINTENANCE', '82A Lambertlodge Ave', to_timestamp('15-12-2008', 'dd-mm-yyyy'), null, null, null, null, null, null, 'TORONTO', '49J-82A Lambertlodge Ave-SW Bin2008/Mpac', 'APPROVED', 0, 200013, 200304, 49);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (412, 691, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'JF-276-280Searle Av', to_timestamp('20-04-2009', 'dd-mm-yyyy'), 'JF-276-280Searle Av', to_timestamp('23-04-2008', 'dd-mm-yyyy'), null, null, null, null, null, 'Add 276A, 276B, 278 Searle Avenue and 319 Brighton Avenue as per JF-CofA-Sever-276-280SearleAv-20090420.pdf and (sketch) 276-280SearleAv-BrightonAv.pdf', 'APPROVED', 0, 203119, 203120, 2401);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (901, 1720, 'REPORT', 'MUNICIPAL NUMBERING LETTER', 'Add 16 AlpineAve-Ent', to_timestamp('10-03-2010', 'dd-mm-yyyy'), 'Add 16 AlpineAve-Ent', to_timestamp('03-06-2009', 'dd-mm-yyyy'), null, null, null, null, null, 'ld/50K21- sever 115 Richview Ave to 109, 111, 115- Torlet 25May2009 for JF', 'APPROVED', 0, 207423, 207450, 10401);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (882, 1680, 'REPORT', 'INHOUSE MAINTENANCE', 'RestoreOneway', null, null, null, null, null, null, null, null, 'Restoring Oneway street segments that are lost when the segment is deleted.', 'APPROVED', 0, 207244, 209522, 13921);
insert into IGE_SOURCE_H (source_id, record_id, source_class, source_type, internal_source_no, internal_source_date, external_source_no, external_source_date, name_prefix, document_number, name_suffix, plan_name, former_municipality, source_comments, source_status, parent_source_id, trans_id_create, trans_id_expire, objectid)
values (1483, 3074, 'REPORT', 'INHOUSE MAINTENANCE', '531-561 Dundas St E', to_timestamp('07-12-2010', 'dd-mm-yyyy'), 'Willison_White Court', to_timestamp('07-12-2010', 'dd-mm-yyyy'), null, null, null, null, null, 'ld/50H11-Add missing entr addresses on 571 Dundas St E, Willison & White Court Place-Mpac/TorPropmap', 'APPROVED', 0, 211477, 211515, 16801);
--commit;
--PROMPT 149 records loaded

-- SET FEEDBACK on
-- SET DEFINE on
--PROMPT Done
